### ISSUE TITLE
Editing API settings affects all Assistants

### ISSUE THREAD

**Issue by sschueller** [chieapp/chie#22]
Chie Version: 0.2.11
Operating System: Manjaro Linux

It appears that if I have two assistant, for example OpenAPI and a local LLM like https://github.com/Mozilla-Ocho/llamafile, when I edit the API credentials for one they also change for the other. There is no way for me to have two different API providers with different API urls and credentials.

**Comment by zcbenz** [comment]
When creating a new assistant, there is a "Create API credentials" button which let's you create separate API credentials for each assistant, otherwise they all share the same credentials.

![Screenshot 2024-10-01 at 8 20 31](https://github.com/user-attachments/assets/bfe69f43-12d0-449c-9692-b63151fde1a8)

**Comment by sschueller** [comment]
Thank you, for some reason I didn't see that.
